### ISSUE TITLE
Release to rubygems.org

### ISSUE THREAD

**Issue by wmakley** [wmakley/tiny_serializer#1]
Need to do a release to rubygems.org, but there is already a gem named simple_serializer

**Comment by trevorrjohn** [comment]
Do you have a plan for this? Could just call it `simpleserializer`?

**Comment by wmakley** [comment]
Well my concerns are:

1. It doesn't _really_ serialize anything in the traditional sense, it just converts Objects to Hashes.
2. I don't really want to introduce the subtle confusion of a single underscore. It seems petty, since the gem of the same name is actually _simpler_ and motivated by the same needs.

In short, I want it to be discoverable as an AMS replacement, and to have the name represent what it actually does. Here are some options I considered:

- simple_hash_stuffer
- simple_hash_mapper
- active_model_hash_mapper

Let me know if anything jumps out at you, I'm open to suggestions. I'd like to push it to rubygems.

**Comment by trevorrjohn** [comment]
Fair enough regarding `simpleserializer`.

To be honest I don't love any of those names. 

I am poking around AMS and kind of like this name: https://github.com/rails-api/active_model_serializers/blob/0-10-stable/lib/active_model/serializable_resource.rb

`SimpleSerializableResource`

**Comment by lucasluitjes** [comment]
How about `tiny_serializer`? Would really love to have this up on rubygems.

**Comment by wmakley** [comment]
Love it, works for me. Stay tuned.

**Comment by wmakley** [comment]
Unfamiliar with what happens in Github when I rename a repo... will everyone's installation break?

**Comment by trevorrjohn** [comment]
Great question, I think it is fine,
https://help.github.com/articles/renaming-a-repository/

**Comment by wmakley** [comment]
Yup, found that! Renamed, tested, and published.

`gem 'tiny_serializer', '~> 2.0.0'` should do the trick!
